#!/bin/sh
# Starts the music file move (nylm-music-move.service, which runs
# `nylm music-move` as user nylm) and returns at once. Takes no arguments.
set -eu
if [ "$#" -ne 0 ]; then
    echo "music-move: takes no arguments" >&2
    exit 2
fi
exec /usr/bin/systemctl start --no-block nylm-music-move.service
