#!/bin/sh
# Turns migrations/*.sql into a C file with one string per migration, in
# filename order. Usage: embed-migrations.sh OUT.c migrations/*.sql
set -eu
out=$1
shift
{
    echo '/* Generated by tools/embed-migrations.sh. Do not edit. */'
    echo 'const char *const migrations[] = {'
    for f in "$@"; do
        echo "    /* $f */"
        sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/    "/' -e 's/$/\\n"/' "$f"
        echo '    ,'
    done
    echo '};'
    echo 'const int migration_count = sizeof migrations / sizeof migrations[0];'
} > "$out"
